# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.5.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.5.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yifei/dev/gnssrecv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yifei/dev/gnssrecv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.5.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.5.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.5.0/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.5.0/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.5.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.5.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	cd /Users/yifei/dev/gnssrecv && $(CMAKE_COMMAND) -E cmake_progress_start /Users/yifei/dev/gnssrecv/CMakeFiles /Users/yifei/dev/gnssrecv/fft/CMakeFiles/progress.marks
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f CMakeFiles/Makefile2 fft/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yifei/dev/gnssrecv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f CMakeFiles/Makefile2 fft/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f CMakeFiles/Makefile2 fft/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f CMakeFiles/Makefile2 fft/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/yifei/dev/gnssrecv && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
fft/CMakeFiles/kiss_fft.dir/rule:
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f CMakeFiles/Makefile2 fft/CMakeFiles/kiss_fft.dir/rule
.PHONY : fft/CMakeFiles/kiss_fft.dir/rule

# Convenience name for target.
kiss_fft: fft/CMakeFiles/kiss_fft.dir/rule

.PHONY : kiss_fft

# fast build rule for target.
kiss_fft/fast:
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f fft/CMakeFiles/kiss_fft.dir/build.make fft/CMakeFiles/kiss_fft.dir/build
.PHONY : kiss_fft/fast

kiss_fft.o: kiss_fft.c.o

.PHONY : kiss_fft.o

# target to build an object file
kiss_fft.c.o:
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f fft/CMakeFiles/kiss_fft.dir/build.make fft/CMakeFiles/kiss_fft.dir/kiss_fft.c.o
.PHONY : kiss_fft.c.o

kiss_fft.i: kiss_fft.c.i

.PHONY : kiss_fft.i

# target to preprocess a source file
kiss_fft.c.i:
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f fft/CMakeFiles/kiss_fft.dir/build.make fft/CMakeFiles/kiss_fft.dir/kiss_fft.c.i
.PHONY : kiss_fft.c.i

kiss_fft.s: kiss_fft.c.s

.PHONY : kiss_fft.s

# target to generate assembly for a file
kiss_fft.c.s:
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f fft/CMakeFiles/kiss_fft.dir/build.make fft/CMakeFiles/kiss_fft.dir/kiss_fft.c.s
.PHONY : kiss_fft.c.s

tools/kfc.o: tools/kfc.c.o

.PHONY : tools/kfc.o

# target to build an object file
tools/kfc.c.o:
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f fft/CMakeFiles/kiss_fft.dir/build.make fft/CMakeFiles/kiss_fft.dir/tools/kfc.c.o
.PHONY : tools/kfc.c.o

tools/kfc.i: tools/kfc.c.i

.PHONY : tools/kfc.i

# target to preprocess a source file
tools/kfc.c.i:
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f fft/CMakeFiles/kiss_fft.dir/build.make fft/CMakeFiles/kiss_fft.dir/tools/kfc.c.i
.PHONY : tools/kfc.c.i

tools/kfc.s: tools/kfc.c.s

.PHONY : tools/kfc.s

# target to generate assembly for a file
tools/kfc.c.s:
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f fft/CMakeFiles/kiss_fft.dir/build.make fft/CMakeFiles/kiss_fft.dir/tools/kfc.c.s
.PHONY : tools/kfc.c.s

tools/kiss_fftnd.o: tools/kiss_fftnd.c.o

.PHONY : tools/kiss_fftnd.o

# target to build an object file
tools/kiss_fftnd.c.o:
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f fft/CMakeFiles/kiss_fft.dir/build.make fft/CMakeFiles/kiss_fft.dir/tools/kiss_fftnd.c.o
.PHONY : tools/kiss_fftnd.c.o

tools/kiss_fftnd.i: tools/kiss_fftnd.c.i

.PHONY : tools/kiss_fftnd.i

# target to preprocess a source file
tools/kiss_fftnd.c.i:
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f fft/CMakeFiles/kiss_fft.dir/build.make fft/CMakeFiles/kiss_fft.dir/tools/kiss_fftnd.c.i
.PHONY : tools/kiss_fftnd.c.i

tools/kiss_fftnd.s: tools/kiss_fftnd.c.s

.PHONY : tools/kiss_fftnd.s

# target to generate assembly for a file
tools/kiss_fftnd.c.s:
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f fft/CMakeFiles/kiss_fft.dir/build.make fft/CMakeFiles/kiss_fft.dir/tools/kiss_fftnd.c.s
.PHONY : tools/kiss_fftnd.c.s

tools/kiss_fftndr.o: tools/kiss_fftndr.c.o

.PHONY : tools/kiss_fftndr.o

# target to build an object file
tools/kiss_fftndr.c.o:
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f fft/CMakeFiles/kiss_fft.dir/build.make fft/CMakeFiles/kiss_fft.dir/tools/kiss_fftndr.c.o
.PHONY : tools/kiss_fftndr.c.o

tools/kiss_fftndr.i: tools/kiss_fftndr.c.i

.PHONY : tools/kiss_fftndr.i

# target to preprocess a source file
tools/kiss_fftndr.c.i:
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f fft/CMakeFiles/kiss_fft.dir/build.make fft/CMakeFiles/kiss_fft.dir/tools/kiss_fftndr.c.i
.PHONY : tools/kiss_fftndr.c.i

tools/kiss_fftndr.s: tools/kiss_fftndr.c.s

.PHONY : tools/kiss_fftndr.s

# target to generate assembly for a file
tools/kiss_fftndr.c.s:
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f fft/CMakeFiles/kiss_fft.dir/build.make fft/CMakeFiles/kiss_fft.dir/tools/kiss_fftndr.c.s
.PHONY : tools/kiss_fftndr.c.s

tools/kiss_fftr.o: tools/kiss_fftr.c.o

.PHONY : tools/kiss_fftr.o

# target to build an object file
tools/kiss_fftr.c.o:
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f fft/CMakeFiles/kiss_fft.dir/build.make fft/CMakeFiles/kiss_fft.dir/tools/kiss_fftr.c.o
.PHONY : tools/kiss_fftr.c.o

tools/kiss_fftr.i: tools/kiss_fftr.c.i

.PHONY : tools/kiss_fftr.i

# target to preprocess a source file
tools/kiss_fftr.c.i:
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f fft/CMakeFiles/kiss_fft.dir/build.make fft/CMakeFiles/kiss_fft.dir/tools/kiss_fftr.c.i
.PHONY : tools/kiss_fftr.c.i

tools/kiss_fftr.s: tools/kiss_fftr.c.s

.PHONY : tools/kiss_fftr.s

# target to generate assembly for a file
tools/kiss_fftr.c.s:
	cd /Users/yifei/dev/gnssrecv && $(MAKE) -f fft/CMakeFiles/kiss_fft.dir/build.make fft/CMakeFiles/kiss_fft.dir/tools/kiss_fftr.c.s
.PHONY : tools/kiss_fftr.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... kiss_fft"
	@echo "... kiss_fft.o"
	@echo "... kiss_fft.i"
	@echo "... kiss_fft.s"
	@echo "... tools/kfc.o"
	@echo "... tools/kfc.i"
	@echo "... tools/kfc.s"
	@echo "... tools/kiss_fftnd.o"
	@echo "... tools/kiss_fftnd.i"
	@echo "... tools/kiss_fftnd.s"
	@echo "... tools/kiss_fftndr.o"
	@echo "... tools/kiss_fftndr.i"
	@echo "... tools/kiss_fftndr.s"
	@echo "... tools/kiss_fftr.o"
	@echo "... tools/kiss_fftr.i"
	@echo "... tools/kiss_fftr.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/yifei/dev/gnssrecv && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

